//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenSoft_Balcao.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItem
    {
        public int Seq_ID { get; set; }
        public int Pedido_ID { get; set; }
        public Nullable<int> Produto_ID { get; set; }
        public int Qtde { get; set; }
        public decimal Valor { get; set; }
        public decimal ValorTotal { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
