//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenSoft_Balcao.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoCoperativa
    {
        public int Cooperativa_ID { get; set; }
        public int Produto_ID { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Cooperativa Cooperativa { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
